package utils;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;

/***
 * <p><b>PledgeReader</b> aims to read configurations from the csv result generated by PLEDGE solver. </p> 
 *
 */
public class PledgeReader {
	
	public static void main(String[] args){
		PledgeReader pr = new PledgeReader("file/jhipster.pledge.40", 40);
		for(List<String> config: pr.configs) System.out.println(config);	
	}
	
	List<List<String>> configs;
	
	public PledgeReader(String path, int num){
		
		File file = new File(path);
		if(!file.exists()){
			System.out.println("No Such File! " + path);
			return;
		}
		
		try {
			configs = getValidConfigs(file);
		} catch (IOException e) {
			System.out.println("Reading File Failed! " + path);
			e.printStackTrace();
		}
	}
	
	/***
	 * <p>To obtain configurations from the csv file generated by <b>Dissimilarity</b> algorithms.</p>
	 * @param file csv result
	 * @return configurations list
	 */
	public List<List<String>> getValidConfigs(File file) throws IOException{
		List<List<String>> configurations = new ArrayList<List<String>>();
		
		FileInputStream fis = new FileInputStream(file);
		BufferedReader br = new BufferedReader(new InputStreamReader(fis));
	 
		String line = null;
		List<String> features = new ArrayList<String>();
		
		while ((line = br.readLine()) != null){
			if(line.contains("->")){
				String[] partition = line.split("->");
				features.add(partition[1]);
			}
			if(line.contains(";")){
				String[] partition = line.split(";");
				List<String> config = new ArrayList<String>();
				for(int m=0; m<partition.length; m++){
					if(partition[m].startsWith("-")){
						config.add("!" + features.get(m));
					}else{
						config.add(features.get(m));
					}
				}
				configurations.add(config);
			}
		}
		
		br.close();
	
		return configurations;
	}
	


}
